from backend.models.alerta_model import AlertaModel
from backend.models.atendimentos_model import AtendimentoModel
from backend.models.medico_profile import MedicoProfile
from backend.models.opcao_resposta_model import OpcaoRespostaModel
from backend.models.paciente_profile import PacienteProfile
from backend.models.pergunta_model import PerguntaModel
from backend.models.resposta_model import RespostaModel
from backend.models.user_model import UserModel
from backend.models.clinica_model import ClinicaModel